import type { SiteContent } from "./types";
import { projectAssets } from "./shared";

/*
 * English version (route "/en"). Same shape as es.ts.
 * "TODO(nacho):" = missing data; hidden in production.
 */

export const en: SiteContent = {
  locale: "en",
  meta: {
    title: "Ignacio Nuñez Valcarce — Product & brand design",
    description:
      "Design student at UdeSA, working on brand and digital product at Inspira RRHH. I look for the problem behind the problem — and build what solves it.",
    ogLocale: "en_US",
  },

  ui: {
    cta: "Let's talk",
    ctaAria: "Let's talk: open contact details",
    seeProjects: "See projects",
    seeCase: "See case",
    backToProjects: "All projects",
    nextProject: "Next project",
    skipToContent: "Skip to content",
    menu: "Menu",
    close: "Close",
    langName: "English",
    langSwitch: "Leer en español",
    caseLabels: {
      problem: "The problem",
      role: "My role",
      process: "Process",
      question: "The question that guided me",
      result: "Outcome",
      learned: "What I learned",
      year: "Year",
      with: "With",
    },
    contact: {
      title: "Let's talk.",
      body: "Projects, internships, a half-baked idea or a question.",
      fields: { firstName: "First name", lastName: "Last name", email: "Email", company: "Company", phone: "Phone", message: "Message" },
      optional: "optional",
      messagePlaceholder: "Tell me what you're up to: a project, an internship, a half-baked idea…",
      errors: {
        required: "This field is required.",
        email: "Check the email — I need it to reply.",
        messageMin: "Tell me a bit more (at least 10 characters).",
        rateLimited: "You sent several messages in a row. Try again in a few minutes.",
      },
      submit: "Send",
      sending: "Sending…",
      success: "Done! I'll get back to you soon.",
      errorPrefix: "It couldn't be sent. Write to me directly at",
      errorFallback: "It couldn't be sent. Please try again in a bit.",
      copy: "Copy",
      copied: "Copied",
      subject: "Hi Nacho —",
      emailLabel: "Email",
    },
    keywords: {
      counter: "words",
      title: "Words that define me",
      hint: "They're hidden across the page, always next to the proof.",
      done: "You found them all. You know a fair bit about me by now — let's talk about the rest.",
    },
    lightbox: { open: "Enlarge photo", prev: "Previous photo", next: "Next photo", close: "Close" },
    filterLabel: "Filter experiments",
    filterAll: "All",
  },

  person: {
    name: "Ignacio Nuñez Valcarce",
    city: "Buenos Aires",
    timezone: "America/Argentina/Buenos_Aires",
    email: "TODO(nacho): mail",
    cv: "TODO(nacho): /cv/cv-ignacio-nunez-valcarce.pdf",
    links: [
      { label: "LinkedIn", href: "https://www.linkedin.com/in/ignacio-nu%C3%B1ez-valcarce-7b870a211/" },
      { label: "GitHub", href: "https://github.com/IgnacioNV" },
    ],
  },

  nav: [
    { id: "proyectos", creative: "Make", label: "Projects" },
    { id: "pienso", creative: "Think", label: "How I think" },
    { id: "laboratorio", creative: "Try", label: "Lab" },
    { id: "quien-soy", creative: "Trace", label: "About" },
    { id: "contacto", creative: "Next", label: "Contact" },
  ],

  keywords: {
    autodidacta: {
      label: "self-taught",
      evidence: "I learned Figma to a professional level almost entirely on my own. Guitar, 100% on my own.",
      section: "quien-soy",
    },
    curioso: {
      label: "curious",
      evidence: "I build things to understand how they work: apps, objects, volleyball stats.",
      section: "laboratorio",
    },
    innovacion: {
      label: "innovation",
      evidence: "SIMA uses machine learning to help detect multiple sclerosis; Trevian, iPhone scanning and 3D printing.",
      section: "proyectos",
    },
    producto: {
      label: "product",
      evidence: "SIMA, Trevian, Study Buddy and Inspira: digital products, not just screens.",
      section: "proyectos",
    },
    creatividad: {
      label: "creativity",
      evidence: "NIHOL's identity came out of interviews: name, logo, palette and tone.",
      section: "proyectos",
    },
    estrategia: {
      label: "strategy",
      evidence: "Identity and digital experience for an HR consultancy, designed for the people who decide.",
      section: "proyectos",
    },
    pensamiento: {
      label: "critical thinking",
      evidence: "Seven questions before opening Figma, and an award-winning video on interfaces and addiction.",
      section: "pienso",
    },
    proyectos: {
      label: "projects",
      evidence: "Seven experiments I started on my own, without anyone asking.",
      section: "laboratorio",
    },
    liderazgo: {
      label: "leadership",
      evidence: "Captain on the Metropolitan and Argentine teams. Graduation speech at the Gran Rex for 3,000+ people.",
      section: "quien-soy",
    },
    equipo: {
      label: "teamwork",
      evidence: "Around 10 years of federated volleyball and three national championships with my club.",
      section: "quien-soy",
    },
    emprendedora: {
      label: "entrepreneurial mindset",
      evidence: "Spot a problem, research it, design it, build the prototype. The founder profile I'm going for.",
      section: "contacto",
    },
  },

  hero: {
    title: "I design decisions, not just screens.",
    titleStart: "I design",
    titleStruck: "screens.",
    titleReplacement: "decisions, not just screens.",
    sub: "I study Design at UdeSA and work on brand and product at Inspira.",
    proofs: ["Design UdeSA", "Inspira RRHH"],
    portrait: {
      src: "/fotos/hero.jpg",
      alt: "Portrait of Ignacio Nuñez Valcarce",
    },
    under: [
      { src: "/fotos/hero-debajo-1.jpg", alt: "TODO(nacho): description of work image 1" },
      { src: "/fotos/hero-debajo-2.jpg", alt: "TODO(nacho): description of work image 2" },
      { src: "/fotos/hero-debajo-3.jpg", alt: "TODO(nacho): description of work image 3" },
    ],
    visual: {
      label: "Photo of Ignacio. Underneath, his projects. Use the arrow keys to reveal and Enter to toggle.",
      toggle: "Toggle between the photo and the work",
    },
  },

  projects: {
    title: "What I've made.",
    lede: "Five [[producto:product]], brand and [[innovacion:innovation]] projects. They all started with the same question: what's going on with the person on the other side.",
    moreTitle: "Also",
    ctaLine: "Want to see more of any of these? Happy to walk you through it.",
    list: [
      {
        slug: "sima",
        name: "SIMA",
        aka: "Sclerosis Intelligent Medical Assistant",
        year: "2024",
        role: ["UX/UI", "Branding"],
        problem: "Helping detect multiple sclerosis from clinical data, with machine learning.",
        with: "Fundación Noemí Frida Kraut",
        tier: "lg",
        ...projectAssets.sima,
        case: {
          problem: [
            "SIMA is a platform that uses artificial intelligence and machine learning to help detect multiple sclerosis from clinical information.",
            "It was developed together with Fundación Noemí Frida Kraut and went through an MVP experience.",
          ],
          role: ["I worked on the UX/UI and the branding.", "TODO(nacho): screens, flows and identity decisions"],
          question: 2,
          process: ["TODO(nacho): SIMA process (research, flows, iterations)"],
          result: ["TODO(nacho): what came out of the MVP experience"],
          learned: [
            "It's the project where most of what I care about overlaps: design, technology, AI, health and social impact.",
            "TODO(nacho): concrete learnings",
          ],
        },
      },
      {
        slug: "inspira",
        name: "Inspira RRHH",
        year: "2026 — now",
        role: ["Brand", "Web", "Visual system"],
        problem: "Identity, [[estrategia:strategy]] and website for an HR consultancy, designed for the people who decide.",
        with: "Inspira Recursos Humanos",
        tier: "lg",
        ...projectAssets.inspira,
        case: {
          problem: [
            "Inspira works in recruitment, psychometric evaluations, training and coaching.",
            "I'm designing their website and visual system, thinking mostly about the HR people who make decisions.",
          ],
          role: [
            "Brand and digital product. The values I'm working toward: people, solvency, seriousness, warmth, trust and human treatment.",
          ],
          question: 6,
          process: ["TODO(nacho): Inspira process"],
          result: ["TODO(nacho): link to the site once it's live"],
          learned: ["A real client: this is where I'm learning how design relates to an organization and to commercial goals."],
        },
      },
      {
        slug: "trevian",
        name: "Trevian",
        facts: [{ label: "Typeface", value: "Onest" }],
        year: "2025",
        role: ["TODO(nacho): your role in Trevian"],
        problem: "A custom orthopedic insole without going anywhere: the insole comes to you.",
        tier: "md",
        ...projectAssets.trevian,
        case: {
          problem: [
            "A personalized orthopedic insole. The foot is scanned with the iPhone's LiDAR, the data is processed with algorithms and AI, and the insole is 3D-fabricated for that one person.",
            "The experience covers scanning, processing and fabrication, with professionals like kinesiologists in the loop.",
          ],
          role: ["TODO(nacho): what you designed in Trevian (app, scan flow, brand, service)"],
          question: 2,
          process: [
            "Scan the foot → process the data → fabricate the insole → a professional in the loop.",
            "TODO(nacho): Trevian process",
          ],
          result: ["TODO(nacho): Trevian outcome"],
          learned: [
            "It mixes product design, technology, user experience, digital fabrication and health. Less a screen, more a whole service.",
            "TODO(nacho): concrete learnings",
          ],
        },
      },
      {
        slug: "nihol",
        name: "NIHOL",
        aka: "Fundación Nietos del Holocausto",
        year: "TODO(nacho): NIHOL year",
        role: ["Naming", "Visual identity", "Tone of voice"],
        problem: "An identity built with [[creatividad:creativity]] and care, out of the stories of the people behind the foundation.",
        with: "Fundación Nietos del Holocausto",
        tier: "md",
        ...projectAssets.nihol,
        case: {
          problem: ["The project started from interviews and conversations with people connected to the foundation."],
          role: ["Name, visual identity, logo, palette, typography and tone of communication."],
          question: 0,
          process: ["TODO(nacho): what came up in the interviews", "TODO(nacho): how you got to the name NIHOL"],
          result: ["TODO(nacho): the final system (logo, palette, type) and why"],
          learned: [
            "My work isn't only interfaces: I care about researching, listening and building an identity out of people and their stories.",
          ],
        },
      },
      {
        slug: "study-buddy",
        name: "Study Buddy",
        year: "2023",
        role: ["UX/UI", "Design"],
        problem: "Helping students aged 10 to 18 study and get organized, with Feynman and Pomodoro.",
        with: "ORT Argentina",
        tier: "sm",
        ...projectAssets["study-buddy"],
        case: {
          problem: [
            "A school project at ORT: an app for students roughly 10 to 18 years old to study and get organized.",
            "It used ideas like the Feynman technique and Pomodoro.",
          ],
          role: ["My role was mainly UX/UI and design."],
          question: 3,
          process: ["TODO(nacho): Study Buddy process"],
          result: ["TODO(nacho): Study Buddy outcome"],
          learned: ["One of my first approaches to designing a digital product. The starting point."],
        },
      },
    ],
  },

  thinking: {
    opening: "I care more about what an interface does to people than how it looks.",
    openingSub: "I look for the problem behind the problem — then I build it.",
    title: "I start with questions, not screens.",
    lede: "Design isn't only how something looks. It's a way to understand an experience and then change it. This is [[pensamiento:critical thinking]] in practice: the questions I keep coming back to.",
    hint: "Pick a question and see where I used it.",
    appliedIn: "Used in",
    reset: "Show all",
    questions: [
      { q: "Why does a person do what they do?", projects: ["nihol", "study-buddy"] },
      { q: "What are they actually feeling?", projects: ["nihol", "sima"] },
      { q: "What's the real problem behind the apparent one?", projects: ["sima", "trevian"] },
      { q: "How does an experience change when you change the interface?", projects: ["study-buddy", "inspira"] },
      { q: "Can technology change a behavior? Should it?", projects: ["study-buddy", "trevian"] },
      { q: "How do you make something useful and also meaningful?", projects: ["sima", "nihol"] },
      { q: "Which invisible decisions does a designer make?", projects: ["inspira", "nihol"] },
    ],
    award: {
      kicker: "World ORT STEM Communication Award · 2025",
      title: "¿Consumimos experiencias o consumimos adicciones?",
      body: [
        "Do we consume experiences, or addictions? A video about interface design, addiction, anxiety and social media — and about our responsibility when we design digital experiences.",
        "It draws on Jonathan Haidt and ideas from Lacan. It won the World ORT STEM Communication Award 2025.",
      ],
      link: "TODO(nacho): video link",
      linkLabel: "Watch the video",
    },
  },

  lab: {
    title: "Things I build to find out.",
    lede: "I'm [[curioso:curious]]: small [[proyectos:projects]], prototypes and ideas I start on my own to understand how things work. I pick something I want to exist and try to make it.",
    tags: {
      pwa: "PWA",
      social: "Social",
      "sport-data": "Sport & data",
      physical: "Physical",
      photo: "Photo",
      meta: "Meta",
    },
    result: { one: "1 experiment in {tag}", other: "{n} experiments in {tag}", all: "{n} experiments" },
    entries: [
      {
        id: "L-01",
        title: "Offline trip companion",
        line: "An experience for a trip through Puglia and Greece that works without signal.",
        tags: ["pwa"],
        status: "TODO(nacho): status",
        note: "TODO(nacho): what you wanted to find out",
      },
      {
        id: "L-02",
        title: "Sticker swap",
        line: "An app to trade World Cup stickers.",
        tags: ["pwa", "social"],
        status: "TODO(nacho): status",
        note: "TODO(nacho): what you wanted to find out",
      },
      {
        id: "L-03",
        title: "Hitster-style music game",
        line: "A PWA inspired by Hitster, for playing with music.",
        tags: ["pwa", "social"],
        status: "TODO(nacho): status",
        note: "TODO(nacho): what you wanted to find out",
      },
      {
        id: "L-04",
        title: "Volleyball stats, less manual",
        line: "Automating part of the stats work that's done by hand today with tools like Data Volley.",
        tags: ["sport-data"],
        status: "Idea",
        note: "Years of federated volleyball showed me from the inside how teams, performance and data work.",
      },
      {
        id: "L-05",
        title: "Objects for a room",
        line: "Concepts for physical objects that mix rooms and technology.",
        tags: ["physical"],
        status: "TODO(nacho): status",
        note: "TODO(nacho): details",
      },
      {
        id: "L-06",
        title: "Photography",
        line: "Street, people, landscapes. It started when my grandfather gave me a professional camera.",
        tags: ["photo"],
        status: "Ongoing",
        note: "TODO(nacho): photo selection (the About gallery appears with 6+ photos in src/data/fotos.ts)",
      },
      {
        id: "L-07",
        title: "This portfolio",
        line: "Designed in the browser, built with Next.js, with Claude as a collaborator.",
        tags: ["meta"],
        status: "v2",
        note: "A portfolio shouldn't only show projects. It should be one.",
      },
    ],
  },

  about: {
    title: "About me.",
    lede: "Design, code, volleyball, guitar and a camera. Not necessarily in that order.",
    portrait: {
      src: "/fotos/roma.jpg",
      alt: "Ignacio wearing sunglasses in front of the Colosseum in Rome",
      caption: "Rome. Tourist mode.",
    },
    story: [
      "I'm from Buenos Aires. I went to high school at ORT on the TIC track (programming, design, technology) and now I study Design at UdeSA.",
      "Along the way I learned something no curriculum covers: almost 10 years of federated volleyball, first at GEBA and then at Club Ciudad de Buenos Aires, with three national championships. That's where I really understood [[equipo:teamwork]], pressure and data.",
      "I was captain in call-ups to the Metropolitan team and the Argentine national team, and I gave ORT's graduation speech at the Gran Rex, together with another student, to more than 3,000 people. Some [[liderazgo:leadership]] had to be involved.",
      "I've played guitar since I was 12 (self-taught). I've been taking photos since my grandfather gave me a professional camera.",
    ],
    stats: [
      { value: 3000, prefix: "+", label: "people at the Gran Rex" },
      { value: 3, label: "national championships" },
      { value: 10, prefix: "~", label: "years of federated volleyball" },
    ],
    photos: [
      { src: "/fotos/voley-01.jpg", alt: "The volleyball team lifting the trophy after winning a championship" },
      { src: "/fotos/trabajando-01.jpg", alt: "TODO(nacho): photo working" },
      { src: "/fotos/guitarra.jpg", alt: "TODO(nacho): photo with the guitar" },
    ],
    timelineTitle: "Path",
    timeline: [
      { when: "Sep 2026 —", title: "Inspira Recursos Humanos", body: "Brand & digital product designer.", current: true },
      { when: "2026 —", title: "Design at UdeSA", body: "Project thinking — plus business, technology, analysis and code around it.", current: true, logos: ["/logos/udesa.svg"] },
      { when: "2025", title: "Graduation speech at the Gran Rex", body: "On behalf of ORT's graduates, to more than 3,000 people.", logos: ["/logos/ort.png"] },
      { when: "2025", title: "World ORT STEM Communication Award", body: "For a video on interface design, addiction and anxiety.", logos: ["/logos/world-ort.svg"] },
      {
        when: "Feb 2025",
        title: "World ORT Ecology Summer School, Panama",
        body: "A course in tropical ecology at Soberanía National Park.",
        logos: ["/logos/world-ort.svg"],
      },
      { when: "TODO(nacho): year", title: "ORT London", body: "TODO(nacho): what ORT London was" },
      {
        when: "2020 — 2025",
        title: "ORT Argentina, TIC track",
        body: "Programming, design, technology and communication. Average around 9.5/10; best marks in English, TIC and Programming.",
        logos: ["/logos/ort.png"],
      },
      { when: "2019", title: "Club Ciudad de Buenos Aires", body: "Volleyball. Three national championships with the club." },
      { when: "2018", title: "GEBA", body: "Started playing federated volleyball." },
      { when: "2013 — 2019", title: "Scuola Italiana Cristoforo Colombo", body: "Primary school.", logos: ["/logos/scuola-italiana.png"] },
    ],
    nowLabel: "Now",
    educationTitle: "Education",
    education: [
      { name: "Universidad de San Andrés", detail: "Design", years: "2026 —", logo: "/logos/udesa.svg", hover: "Design · 2026–" },
      { name: "ORT Argentina", detail: "Technical high school, TIC track", years: "2020 — 2025", logo: "/logos/ort.png", hover: "TIC · 2020–2025" },
    ],
    languagesTitle: "Languages",
    languages: [
      { name: "Spanish", level: "Native" },
      { name: "English", level: "Upper-intermediate (B2) · Cambridge B2 First (FCE)" },
      { name: "Italian", level: "Advanced · fluent — studied from age 4 to 12 at Scuola Italiana" },
    ],
    toolsTitle: "What I work with",
    toolsLede:
      "I'm pretty [[autodidacta:self-taught]]: I learned Figma to a professional level almost entirely on my own. I'm not a software engineer and don't want to pretend to be one; code is how I stop depending on someone else to find out if an idea works. I use AI to make things, not to design for me.",
    stages: ["Understand", "Prototype", "Build"],
    tools: [
      { name: "Conversations", icon: "", stages: [0] },
      { name: "Interviews", icon: "", stages: [0] },
      { name: "Research", icon: "", stages: [0] },
      { name: "Figma", icon: "figma", stages: [1] },
      { name: "Figma Make", icon: "figma", stages: [1] },
      { name: "Illustrator", icon: "illustrator", stages: [1] },
      { name: "HTML / CSS / JS", icon: "html", stages: [1, 2] },
      { name: "React", icon: "react", stages: [2] },
      { name: "Next.js", icon: "next", stages: [2] },
      { name: "GitHub", icon: "github", stages: [2] },
      { name: "Premiere Pro", icon: "premiere", stages: [2] },
      { name: "Cursor", icon: "cursor", stages: [1, 2] },
      { name: "Claude", icon: "claude", stages: [1, 2] },
    ],
    nowTitle: "Right now",
    nowLabels: { reading: "Reading", listening: "Listening to", building: "Building" },
    galleryTitle: "Photos I took",
    galleryLede: "Street, people, landscapes.",
  },

  closing: {
    title: "Where I'm going.",
    body: [
      "I haven't picked a label yet, on purpose. I'm into the space between design, technology and business: spotting a problem, researching it, understanding the people in it, thinking a strategy, designing the solution and building a prototype that works.",
      "Call it an [[emprendedora:entrepreneurial mindset]]: somewhere between product designer, product manager and innovator. In digital products, startups, tech companies — or my own projects.",
    ],
    spacesTitle: "Territories I'm exploring",
    spaces: [
      "Product Design",
      "UX/UI",
      "Interaction design",
      "Product Management",
      "Strategy",
      "Innovation",
      "Startups",
      "AI",
      "Branding",
      "User research",
      "Behavioral psychology",
      "Digital business",
    ],
    ctaTitle: "Got an interesting problem?",
    ctaBody: "I'm looking for internships and first roles in product and UX, plus freelance brand and web projects. If any of this is useful to you, let's talk.",
    cvLabel: "Download CV",
  },

  footer: "v2 · 2026. Designed and built in Buenos Aires, with Next.js and Claude.",
};
